version: "3.8"

services:
  streaming-app:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/scalable-streaming-analytics-17002e5f0ca4.json
    command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --no-browser
