version: "3.8"

services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow
    restart: always
    ports:
      - "8080:8080" # Airflow UI
    volumes:
      - .:/app
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__FERNET_KEY: 1uXNlUfK6wQLYxv_ylZM2TnPc62x2zBvL8-OUzJlOoI=
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
