services:
  airflow-jupyter:
    build: .
    container_name: airflow-jupyter
    ports:
      - "8080:8080"
      - "8888:8888"
    volumes:
      - ./airflow:/app/airflow
      - ./notebooks:/app/notebooks
      - ./.secrets:/app/.secrets
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/.secrets/gcp-key.json
