services:
  airflow-jupyter:
    build: .
    container_name: airflow-jupyter
    ports:
      - "8888:8888"
      - "8080:8080"
    volumes:
      - ./notebooks:/app/notebooks
      - ./airflow:/app/airflow
      - ./.secrets/gcp-key.json:/app/.secrets/gcp-key.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/.secrets/gcp-key.json
